"""Add database models

Revision ID: 5454ba6f4b4f
Revises:
Create Date: 2022-08-24 17:44:15.672318

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5454ba6f4b4f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "button",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_button_id"), "button", ["id"], unique=False)
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "buttonmessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_buttonmessage_id"), "buttonmessage", ["id"], unique=False)
    op.create_table(
        "carouselmessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_carouselmessage_id"), "carouselmessage", ["id"], unique=False
    )
    op.create_table(
        "textmessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_textmessage_id"), "textmessage", ["id"], unique=False)
    op.create_table(
        "way",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin_message_id", sa.Integer(), nullable=False),
        sa.Column("destination_message_id", sa.Integer(), nullable=False),
        sa.Column("condition", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_message_id"],
            ["message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_way_id"), "way", ["id"], unique=False)
    op.create_table(
        "card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["carouselmessage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_card_id"), "card", ["id"], unique=False)
    op.create_table(
        "messagebutton",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["button.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["buttonmessage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messagebutton_id"), "messagebutton", ["id"], unique=False)
    op.create_table(
        "cardbutton",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.id"],
        ),
        sa.ForeignKeyConstraint(["id"], ["button.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cardbutton_id"), "cardbutton", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cardbutton_id"), table_name="cardbutton")
    op.drop_table("cardbutton")
    op.drop_index(op.f("ix_messagebutton_id"), table_name="messagebutton")
    op.drop_table("messagebutton")
    op.drop_index(op.f("ix_card_id"), table_name="card")
    op.drop_table("card")
    op.drop_index(op.f("ix_way_id"), table_name="way")
    op.drop_table("way")
    op.drop_index(op.f("ix_textmessage_id"), table_name="textmessage")
    op.drop_table("textmessage")
    op.drop_index(op.f("ix_carouselmessage_id"), table_name="carouselmessage")
    op.drop_table("carouselmessage")
    op.drop_index(op.f("ix_buttonmessage_id"), table_name="buttonmessage")
    op.drop_table("buttonmessage")
    op.drop_table("message")
    op.drop_index(op.f("ix_button_id"), table_name="button")
    op.drop_table("button")
    # ### end Alembic commands ###
